# Generated by Django 4.2.1 on 2023-05-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='PhoneNumber',
            field=models.CharField(max_length=60, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='SpecialityName',
            field=models.CharField(max_length=300, verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Employment',
            field=models.CharField(max_length=500, verbose_name='Трудоустройство'),
        ),
        migrations.AlterField(
            model_name='student',
            name='EndCollege',
            field=models.DateField(verbose_name='Окончание колледжа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='FatherName',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Group',
            field=models.CharField(max_length=200, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='LastName',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='PhoneNumber',
            field=models.CharField(max_length=60, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Speciality',
            field=models.CharField(max_length=200, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='CreatedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оздания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.speciality', verbose_name='Специальность'),
        ),
    ]
